# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-03 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20200229_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='expected_result',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='steps_to_reproduce',
        ),
        migrations.AddField(
            model_name='issue',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
