# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-03 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20200303_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(default='', max_length=254),
        ),
    ]
