# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-05 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug', models.CharField(default='', max_length=254)),
                ('feature', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_type',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.ManyToManyField(to='issues.IssueType'),
        ),
    ]
