# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-05 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20200305_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_type',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Feature', 'Feature')], max_length=30),
        ),
        migrations.DeleteModel(
            name='IssueType',
        ),
    ]
