# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-06 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_auto_20200305_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='price',
            field=models.DecimalField(decimal_places=2, default='5', max_digits=6),
        ),
        migrations.AlterField(
            model_name='issue',
            name='actual_Results',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='issue',
            name='expected_Results',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='issue',
            name='step_to_Reproduce',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
