# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-07 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20200306_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
