# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-10 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('ToDo', 'ToDo'), ('InDevelopment', 'InDevelopment'), ('Fixed', 'Fixed'), ('InTest', 'InTest'), ('Done', 'Done')], max_length=30),
        ),
    ]
