# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_auto_20200312_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='votes_required',
            field=models.IntegerField(default=0),
        ),
    ]
