# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-15 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_issue_votes_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='', max_length=1000)),
                ('comment_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='Issue',
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='issue',
            name='root_cause',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='issue',
            name='votes_required',
            field=models.IntegerField(default='100'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='Issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Issue'),
        ),
    ]
