# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-20 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0018_auto_20200320_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
