# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-20 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0019_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Issue',
            new_name='issue',
        ),
    ]
